# Generated by Django 2.2.16 on 2022-03-16 18:16

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220311_1411'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follower',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(_negated=True, following=django.db.models.expressions.F('user')), models.Q(_negated=True, user=django.db.models.expressions.F('following')), _connector='OR'), fields=('user', 'following'), name='unique_follower'),
        ),
    ]
